

server:
  port: 8501
spring:
  application:
    name: winonaapp
  datasource:
    url: jdbc:mysql://rm-uf6evwz9y63o034btlo.mysql.rds.aliyuncs.com:3306/fanta22?useUnicode=true&characterEncoding=UTF-8
    username: fanta2022
    password: 1234qwer!@#$
    driverClassName: com.mysql.jdbc.Driver
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10
  jpa:
    database: MYSQL
    showSql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect

  redis:
    lettuce:
      pool:
        max-wait: -1
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 6000
    password:
    cluster:
      nodes: 172.19.153.214:7001,172.19.153.214:7002,172.19.153.214:7003,172.19.153.214:7004,172.19.153.214:7005,172.19.153.214:7006


  data:
    redis:
      repositories:
        enabled: false
  mvc:
    view:
      prefix: /
      suffix: .html

  thymeleaf:
    cache: false
    prefix: classpath:/templates/


  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  task:
    scheduling:
      pool:
        size: 10

